"""Unit tests for FakeStelePromotionPort.

Proves: default COMMITTED outcome, configurable FAILED/INVALIDATED,
call recording (FakeCommitCall), artifact_hash integrity, and
run_id echo (the join-key contract).
"""

import hashlib
import uuid

from agentsync.kanon.models import PromotionState, SkillCandidate
from agentsync.kanon.stele_port import FakeCommitCall, FakeStelePromotionPort

_RUN_ID = "aaaabbbb-0000-0000-0000-000000000001"


def _candidate(content: str = "some skill content", dir_name: str = "my-skill") -> SkillCandidate:
    return SkillCandidate(content=content, dir_name=dir_name)


# ---------------------------------------------------------------------------
# Default outcome
# ---------------------------------------------------------------------------

def test_default_outcome_is_committed():
    port = FakeStelePromotionPort()
    artifact = port.commit_artifact(_candidate(), _RUN_ID)
    assert artifact.state is PromotionState.COMMITTED


def test_committed_artifact_fields_are_populated():
    port = FakeStelePromotionPort()
    artifact = port.commit_artifact(_candidate("hello skill"), _RUN_ID)
    assert artifact.artifact_hash != ""
    assert artifact.record_id != ""
    assert artifact.run_id != ""


# ---------------------------------------------------------------------------
# Configurable outcomes
# ---------------------------------------------------------------------------

def test_failed_outcome():
    port = FakeStelePromotionPort(outcome=PromotionState.FAILED)
    artifact = port.commit_artifact(_candidate(), _RUN_ID)
    assert artifact.state is PromotionState.FAILED


def test_invalidated_outcome():
    port = FakeStelePromotionPort(outcome=PromotionState.INVALIDATED)
    artifact = port.commit_artifact(_candidate(), _RUN_ID)
    assert artifact.state is PromotionState.INVALIDATED


# ---------------------------------------------------------------------------
# Call recording (FakeCommitCall)
# ---------------------------------------------------------------------------

def test_calls_starts_empty():
    port = FakeStelePromotionPort()
    assert port.calls() == []
    assert port.call_count() == 0


def test_calls_records_each_invocation():
    port = FakeStelePromotionPort()
    rid1 = str(uuid.uuid4())
    rid2 = str(uuid.uuid4())
    c1 = _candidate("content one", "skill-one")
    c2 = _candidate("content two", "skill-two")
    port.commit_artifact(c1, rid1)
    port.commit_artifact(c2, rid2)
    assert port.call_count() == 2
    assert port.calls()[0].candidate.dir_name == "skill-one"
    assert port.calls()[0].run_id == rid1
    assert port.calls()[1].candidate.dir_name == "skill-two"
    assert port.calls()[1].run_id == rid2


def test_calls_returns_snapshot_not_live_list():
    """calls() must return a copy; modifying it must not affect the port state."""
    port = FakeStelePromotionPort()
    port.commit_artifact(_candidate(), _RUN_ID)
    snapshot = port.calls()
    snapshot.clear()
    assert port.call_count() == 1


def test_calls_are_fake_commit_call_instances():
    port = FakeStelePromotionPort()
    port.commit_artifact(_candidate(), _RUN_ID)
    assert isinstance(port.calls()[0], FakeCommitCall)


# ---------------------------------------------------------------------------
# run_id echo — the join-key contract
# ---------------------------------------------------------------------------

def test_artifact_run_id_echoes_passed_run_id():
    """The Fake must echo run_id back in the artifact so callers can assert the join key."""
    port = FakeStelePromotionPort()
    expected = str(uuid.uuid4())
    artifact = port.commit_artifact(_candidate(), expected)
    assert artifact.run_id == expected


def test_different_run_ids_produce_different_artifact_run_ids():
    port = FakeStelePromotionPort()
    rid1 = str(uuid.uuid4())
    rid2 = str(uuid.uuid4())
    a1 = port.commit_artifact(_candidate("x"), rid1)
    a2 = port.commit_artifact(_candidate("x"), rid2)
    assert a1.run_id == rid1
    assert a2.run_id == rid2
    assert a1.run_id != a2.run_id


# ---------------------------------------------------------------------------
# artifact_hash integrity
# ---------------------------------------------------------------------------

def test_artifact_hash_is_sha256_of_content():
    port = FakeStelePromotionPort()
    content = "deterministic content for hash check"
    artifact = port.commit_artifact(_candidate(content), _RUN_ID)
    expected = hashlib.sha256(content.encode()).hexdigest()
    assert artifact.artifact_hash == expected


def test_different_content_gives_different_hash():
    port = FakeStelePromotionPort()
    a1 = port.commit_artifact(_candidate("alpha"), _RUN_ID)
    a2 = port.commit_artifact(_candidate("beta"), _RUN_ID)
    assert a1.artifact_hash != a2.artifact_hash


# ---------------------------------------------------------------------------
# record_id is unique per call (generated by the Fake, not passed in)
# ---------------------------------------------------------------------------

def test_record_id_is_unique_across_calls():
    port = FakeStelePromotionPort()
    a1 = port.commit_artifact(_candidate("x"), str(uuid.uuid4()))
    a2 = port.commit_artifact(_candidate("x"), str(uuid.uuid4()))
    assert a1.record_id != a2.record_id
